# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: required
    python: '3.7'

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - sudo apt-get update
  - pip install --upgrade pip setuptools

install:
  - pip install -r requirements.txt
  - pip install nose>=1.3.7 coverage codecov pytest>=3.0.5
  - python setup.py build
  - python setup.py build_ext --inplace

before_script:
  - mkdir output

script:
  - nosetests -v --exe --with-xunit --with-coverage --cover-package=maxflow

after_success:
  - python setup.py install
  - codecov # PUBLIC project
  # - coverage report && coverage xml
  # - python-codacy-coverage -r coverage.xml
