name: PyMCubes

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools cython
          python -m pip install -r requirements.txt
      - name: Build the package
        run: |
          python setup.py build_ext --inplace
      - name: Test and coverage
        run: |
          python -m pip install pycollada
          python -m pip install pytest>=7.2.0 pytest-cov>=4.0 codecov
          mkdir output
          python -m pytest --cov=mcubes --cov-report=xml
          codecov
      - name: Flake8
        run: |
          python -m pip install flake8
          flake8 .
